version: '3'

services:
  back-end:
    build: 
      context: ./docker      
    ports:
      - 3000:3000
    volumes:
      - ../.:/home/node/app
  
  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: getpetdb